on:
  push:
    tags: 
      - "x*"
      - "p*"
      - "b*"
      - "v*"

name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v1
        with: 
          go-version: 1.15.x
      - name: Get code
        run: |
          git clone https://github.com/rprx/v2ray-vless.git && mv v2ray-vless/* $PWD && rm -rf v2ray-vless

      - name: Create Release
        id: create_release
        uses: monkeyWie/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Gain Dockerfile
        run: |
          mkdir docker-build
          wget -O docker-build/Dockerfile https://raw.githubusercontent.com/charlieethan/vless-build/master/src/Dockerfile
          wget -O docker-build/config.json https://raw.githubusercontent.com/charlieethan/vless-build/master/src/config.json
          wget -O docker-build/v2ray.sh https://raw.githubusercontent.com/charlieethan/vless-build/master/src/v2ray.sh
      
      - name: Build and push
        run: |
          cd docker-build
          docker buildx build --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
          --output "type=image,push=true" \
          --tag "${{ secrets.DOCKER_USERNAME }}/vless:latest" \
          --file Dockerfile .
