on:
  schedule:
    - cron: "*/2 * * * *"

name: Update vless
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cd release && git pull